
App.Verbosity     = TRACE

WoL.Target        = 192.168.178.255
WoL.Port          = 9
WoL.Mac           = 01:02:03:04:05:06
WoL.Interval      = 30

NAS.Shutdown      = 60
NAS.Script        = ./etc/nas_mount.sh

Service.Interface = 0.0.0.0
Service.Port      = 8000
Service.Grace     = 30
