
App.Verbosity     = TRACE

WoL.Target        = 192.168.178.15
WoL.Port          = 9
WoL.Mac           = 01:02:03:04:05:06
WoL.Interval      = 5

NAS.Shutdown      = 60

Service.Interface = 0.0.0.0
Service.Port      = 8000
Service.Grace     = 30
