/* Configuration for buffalo_nas_ctl generated by Alire */
#ifndef BUFFALO_NAS_CTL_CONFIG_H
#define BUFFALO_NAS_CTL_CONFIG_H

#define CRATE_VERSION "0.1.0-dev"
#define CRATE_NAME "buffalo_nas_ctl"

#define ALIRE_HOST_OS "linux"

#define ALIRE_HOST_ARCH "x86_64"

#define ALIRE_HOST_DISTRO "debian"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  3

#endif
